name: Publish

on:
  push:
    tags: ['v*']

jobs:
  publish:
    if: github.repository == 'brc-dd/deno-run'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - run: deno publish
